export const RomulusCards = [
    {
        id: 1,
        battleCard: " https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Archer.png",
        class: "Ranged",
        display_class: "Ranged",
        name: "Archer",
        disPlay_name: "Archer",
        strength: 3,
        ability: "Volley",
        ability_desc: "Volley - When you play the archer card, all other archers from your hand get played automatically.",
        lock: false
    },
    {
        id: 2,
        battleCard: "https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Archer.png",
        class: "Ranged",
        display_class: "Ranged",
        name: "Archer",
        disPlay_name: "Archer",
        strength: 3,
        ability: "Volley",
        ability_desc: "Volley - When you play the archer card, all other archers from your hand get played automatically.",
        lock: false
    },
    {
        id: 3,
        battleCard: "https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Archer.png",
        class: "Ranged",
        display_class: "Ranged",
        name: "Archer",
        disPlay_name: "Archer",
        strength: 3,
        ability: "Volley",
        ability_desc: "Volley - When you play the archer card, all other archers from your hand get played automatically.",
        lock: false
    },
    {
        id: 4,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Mounted Archer.png',
        strength: 4,
        class: "Ranged",
        display_class: "Ranged",
        name: "Mounted_Archer",
        disPlay_name: "Mounted Archer",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 5,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Mounted Archer.png',
        strength: 4,
        class: "Ranged",
        display_class: "Ranged",
        name: "Mounted_Archer",
        disPlay_name: "Mounted Archer",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 6,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Mounted Archer.png',
        strength: 4,
        class: "Ranged",
        display_class: "Ranged",
        name: "Mounted_Archer",
        disPlay_name: "Mounted Archer",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 7,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Aristocrat.png',
        strength: 0,
        class: "Politician",
        display_class: "Politician",
        name: "Aristocrat",
        disPlay_name: "Aristocrat",
        ability: "Diplomat",
        ability_desc: "Diplomat - Pick a card out of your legion and put it in your hand.",
        lock: false
    },
    {
        id: 8,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Barbarians.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Barbarians",
        disPlay_name: "Barbarians",
        ability: "Wild_Animals",
        ability_desc: "Wild Animals - Remove 1 Strength from your opponent’s Light Soldier class for each Barbarian in play.",
        lock: false
    },
    {
        id: 9,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Barbarians.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Barbarians",
        disPlay_name: "Barbarians",
        ability: "Wild_Animals",
        ability_desc: "Wild Animals - Remove 1 Strength from your opponent’s Light Soldier class for each Barbarian in play.",
        lock: false
    },
    {
        id: 10,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Barbarians.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Barbarians",
        disPlay_name: "Barbarians",
        ability: "Wild_Animals",
        ability_desc: "Wild Animals - Remove 1 Strength from your opponent’s Light Soldier class for each Barbarian in play.",
        lock: false
    },
    {
        id: 11,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Barbarians.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Barbarians",
        disPlay_name: "Barbarians",
        ability: "Wild_Animals",
        ability_desc: "Wild Animals - Remove 1 Strength from your opponent’s Light Soldier class for each Barbarian in play.",
        lock: false
    },
    {
        id: 12,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Consul.png',
        strength: 0,
        class: "Politician",
        display_class: "Politician",
        name: "Consul",
        disPlay_name: "Consul",
        ability: "Man_of_the_People",
        ability_desc: "Man of the People - Play on top of any other class to double their overall strength.",
        lock: false
    },
    {
        id: 13,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Decaea.png',
        strength: 7,
        class: "Mounted_Soldier",
        display_class: "Mounted Soldier",
        name: "Decaea",
        disPlay_name: "Decaea",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 14,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Exploratores.png',
        strength: 2,
        class: "Scout",
        display_class: "Scout",
        name: "Exploratores",
        disPlay_name: "Exploratores",
        ability: "Eyes_on_the_Prize",
        ability_desc: "Eyes on the Prize - Choose two cards from your opponent's hand and look at them, Discard one.",
        lock: false
    },
    {
        id: 15,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Exploratores.png',
        strength: 2,
        class: "Scout",
        display_class: "Scout",
        name: "Exploratores",
        disPlay_name: "Exploratores",
        ability: "Eyes_on_the_Prize",
        ability_desc: "Eyes on the Prize - Choose two cards from your opponent's hand and look at them, Discard one.",
        lock: false
    },
    {
        id: 16,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Heavy Cavalry.png',
        strength: 6,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Heavy_Cavalry",
        disPlay_name: "Heavy Cavalry",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 17,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Heavy Cavalry.png',
        strength: 6,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Heavy_Cavalry",
        disPlay_name: "Heavy Cavalry",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 18,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Heavy Cavalry.png',
        strength: 6,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Heavy_Cavalry",
        disPlay_name: "Heavy Cavalry",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 19,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Javelins.png',
        strength: 3,
        class: "Ranged",
        display_class: "Ranged",
        name: "Javelin",
        disPlay_name: "Javelin",
        ability: "Pila",
        ability_desc: "Pila - When you play a javelin card, discard an opponent's card lower or equal to the strength of 3.Discard the Javelin after use.",
        lock: false
    },
    {
        id: 20,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Javelins.png',
        strength: 3,
        class: "Ranged",
        display_class: "Ranged",
        name: "Javelin",
        disPlay_name: "Javelin",
        ability: "Pila",
        ability_desc: "Pila - When you play a javelin card, discard an opponent's card lower or equal to the strength of 3.Discard the Javelin after use.",
        lock: false
    },
    {
        id: 21,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Javelins.png',
        strength: 3,
        class: "Ranged",
        display_class: "Ranged",
        name: "Javelin",
        disPlay_name: "Javelin",
        ability: "Pila",
        ability_desc: "Pila - When you play a javelin card, discard an opponent's card lower or equal to the strength of 3.Discard the Javelin after use.",
        lock: false
    },
    {
        id: 22,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Julius.png',
        strength: 5,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Julius",
        disPlay_name: "Julius",
        ability: "Strategist",
        ability_desc: " Strategist - Increase the strength of Heavy Soldiers by 25% (rounding up).",
        lock: false
    },
    {
        id: 23,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Light Infantry.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Light_Infantry",
        disPlay_name: "Light Infantry",
        ability: "Morale_Boost",
        ability_desc: "Morale Boost - For every light infantry card in play, double their strength.",
        lock: false
    },
    {
        id: 24,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Light Infantry.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Light_Infantry",
        disPlay_name: "Light Infantry",
        ability: "Morale_Boost",
        ability_desc: "Morale Boost - For every light infantry card in play, double their strength.",
        lock: false
    },
    {
        id: 25,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Light Infantry.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Light_Infantry",
        disPlay_name: "Light Infantry",
        ability: "Morale_Boost",
        ability_desc: "None",
        lock: false
    },

    {
        id: 26,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Light Infantry.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Light_Infantry",
        disPlay_name: "Light Infantry",
        ability: "Morale_Boost",
        ability_desc: "Morale Boost - For every light infantry card in play, double their strength.",
        lock: false
    },
    {
        id: 27,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Principes.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Principes",
        disPlay_name: "Principes",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 28,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Principes.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Principes",
        disPlay_name: "Principes",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 29,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Principes.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Principes",
        disPlay_name: "Principes",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 30,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Romulus.png',
        strength: 10,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        disPlay_name: "Romulus",
        name: "Romulus",
        ability: "Our_Fearless_Leader",
        ability_desc: "Our Fearless Leader - Add 1 strength for every Romulus card on the field.",
        lock: false
    },
    {
        id: 31,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Scipio.png ',
        strength: 8,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Scipio",
        disPlay_name: "Scipio",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 32,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Scorpius.png',
        strength: 7,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Scorpius",
        disPlay_name: "Scorpius",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 33,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Tibia.png',
        strength: 6,
        class: "Ranged",
        display_class: "Ranged",
        name: "Tibia",
        disPlay_name: "Tibia",
        ability: "Dead_Eye",
        ability_desc: " Dead Eye - Send an enemy of up to equal strength to your opponents discard pile.",
        lock: false
    },
    {
        id: 34,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Tortuga.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Tortuga",
        disPlay_name: "Tortuga",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 35,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Tortuga.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Tortuga",
        disPlay_name: "Tortuga",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 36,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Tortuga.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Tortuga",
        disPlay_name: "Tortuga",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 37,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Triarii.png',
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Triarii",
        disPlay_name: "Triarii",
        ability: "None",
        ability_desc: "None",
        lock: false
    },

    {
        id: 38,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Triarii.png',
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Triarii",
        disPlay_name: "Triarii",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 39,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Triarii.png',
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Triarii",
        disPlay_name: "Triarii",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 40,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/romus-cards/vEmpire card Triarii.png',
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Triarii",
        disPlay_name: "Triarii",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 42,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Fog of War.png',
        strength: 0,
        class: "Status_Effect",
        display_class: "Status Effect",
        name: "Fog_of_War",
        disPlay_name: "Fog of War",
        ability: "Fog_of_War",
        ability_desc: "Fog of War - Halve the strength of all Ranged Troops on the field.",
        lock: false
    },
    {
        id: 43,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Fog of War.png',
        strength: 0,
        class: "Status_Effect",
        display_class: "Status Effect",
        name: "Fog_of_War",
        disPlay_name: "Fog of War",
        ability: "Fog_of_War",
        ability_desc: "Fog of War - Halve the strength of all Ranged Troops on the field.",
        lock: false
    },
    {
        id: 45,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Reinforcements.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Reinforcements",
        disPlay_name: "Reinforcements",
        ability: "Reinforcements",
        ability_desc: "Reinforcements - Pick a card from your Legion and put it in your hand.",
        lock: false
    },
    {
        id: 46,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Reinforcements.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Reinforcements",
        disPlay_name: "Reinforcements",
        ability: "Reinforcements",
        ability_desc: "Reinforcements - Pick a card from your Legion and put it in your hand.",
        lock: false
    },
    {
        id: 47,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Sudis.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Sudis",
        disPlay_name: "Sudis",
        ability: "Sudis",
        ability_desc: "Sudis - When you play this card, the first troop played in the next round is discarded.",
        lock: false
    },
    {
        id: 48,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Sudis.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Sudis",
        disPlay_name: "Sudis",
        ability: "Sudis",
        ability_desc: "Sudis - When you play this card, the first troop played in the next round is discarded.",
        lock: false
    },
    {
        id: 49,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Laconian Shib.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Laconian_Shib",
        disPlay_name: "Laconian Shib",
        ability: "Laconian_Shib",
        ability_desc: "Laconian Shib- Reduce the Strength of all soldiers on foot by 1.",
        lock: false
    },
    {
        id: 50,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Laconian Shib.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Laconian_Shib",
        disPlay_name: "Laconian Shib",
        ability: "Laconian_Shib",
        ability_desc: "Laconian Shib- Reduce the Strength of all soldiers on foot by 1.",
        lock: false
    },
    {
        id: 44,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Praetorian Guard.png',
        strength: 0,
        class:"Utility",
        display_class:"Utility",
        name:"Praetorian_Guard",
        disPlay_name:"Praetorian Guard",
        ability: "Praetorian_Guard",
        ability_desc: "Praetorian Guard - Attach this card to any other troop to protect them from one negative effect from a enemy card. Discard after that attack.",
        lock:false
    },
    {
        id: 51,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Praetorian Guard.png',
        strength: 0,
        class:"Utility",
        display_class:"Utility",
        name:"Praetorian_Guard",
        disPlay_name:"Praetorian Guard",
        ability: "Praetorian_Guard",
        ability_desc: "Praetorian Guard - Attach this card to any other troop to protect them from one negative effect from a enemy card. Discard after that attack.",
        lock:false
    },
    {
        id: 41,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire+card+Filibuster.png',
        strength: 0,
        class: "Status_Effect",
        display_class: "Status_Effect",
        name: "Filibuster",
        disPlay_name: "Filibuster",
        ability: "Filibuster",
        ability_desc: "Filibuster - Negate the effect of any active politician card."
    },
    {
        id: 52,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire+card+Filibuster.png',
        strength: 0,
        class: "Status_Effect",
        display_class: "Status_Effect",
        name: "Filibuster",
        disPlay_name: "Filibuster",
        ability: "Filibuster",
        ability_desc: "Filibuster - Negate the effect of any active politician card."
    },
]

export const RemusCards = [
    {
        id: 1,
        battleCard: "https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Auxiliary.png",
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Auxiliary",
        disPlay_name: "Auxiliary",
        ability: "Expendable",
        ability_desc: "Expendable - When an Auxiliary card is discarded, you can replace it with a previously discarded Auxiliary once per round.",
        lock: false
    },
    {
        id: 49,
        battleCard: "https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Auxiliary.png",
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Auxiliary",
        disPlay_name: "Auxiliary",
        ability: "Expendable",
        ability_desc: "Expendable - When an Auxiliary card is discarded, you can replace it with a previously discarded Auxiliary once per round.",
        lock: false
    },
    {
        id: 50,
        battleCard: "https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Auxiliary.png",
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Auxiliary",
        disPlay_name: "Auxiliary",
        ability: "Expendable",
        ability_desc: "Expendable - When an Auxiliary card is discarded, you can replace it with a previously discarded Auxiliary once per round.",
        lock: false
    },
    {
        id: 51,
        battleCard: "https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Auxiliary.png",
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Auxiliary",
        disPlay_name: "Auxiliary",
        ability: "Expendable",
        ability_desc: "Expendable - When an Auxiliary card is discarded, you can replace it with a previously discarded Auxiliary once per round.",
        lock: false
    },
    {
        id: 2,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Cataphract.png',
        strength: 6,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Cataphract",
        disPlay_name: "Cataphract",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 3,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Cataphract.png',
        strength: 6,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Cataphract",
        disPlay_name: "Cataphract",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 4,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Cataphract.png',
        strength: 6,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Cataphract",
        disPlay_name: "Cataphract",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 5,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Challus.png',
        strength: 7,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Challus",
        disPlay_name: "Challus",
        ability: "Rally",
        ability_desc: "Rally - Increase all other Light Soldier troops strength by 1.",
        lock: false
    },
    {
        id: 6,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Crossbowman.png',
        strength: 3,
        class: "Ranged",
        display_class: "Ranged",
        name: "Crossbowman",
        disPlay_name: "Crossbowman",
        ability: "Efficiency",
        ability_desc: " Efficiency - add 1 to your overall strength for each enemy Light Soldier card on the battlefield.",
        lock: false
    },
    {
        id: 7,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Crossbowman.png',
        strength: 3,
        class: "Ranged",
        display_class: "Ranged",
        name: "Crossbowman",
        disPlay_name: "Crossbowman",
        ability: "Efficiency",
        ability_desc: " Efficiency - add 1 to your overall strength for each enemy Light Soldier card on the battlefield.",
        lock: false
    },
    {
        id: 8,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Crossbowman.png',
        strength: 3,
        class: "Ranged",
        display_class: "Ranged",
        name: "Crossbowman",
        disPlay_name: "Crossbowman",
        ability: "Efficiency",
        ability_desc: " Efficiency - add 1 to your overall strength for each enemy Light Soldier card on the battlefield.",
        lock: false
    },
    {
        id: 9,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Equites.png',
        strength: 3,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Equites",
        disPlay_name: "Equites",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 10,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Equites.png',
        strength: 3,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Equites",
        disPlay_name: "Equites",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 11,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Equites.png',
        strength: 3,
        class: "Mounted_Troops",
        display_class: "Mounted Troops",
        name: "Equites",
        disPlay_name: "Equites",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 12,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Hastati.png',
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Hastati",
        disPlay_name: "Hastati",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 13,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Hastati.png',
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Hastati",
        disPlay_name: "Hastati",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 14,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Hastati.png',
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Hastati",
        disPlay_name: "Hastati",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 15,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Hastati.png',
        strength: 2,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Hastati",
        disPlay_name: "Hastati",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 16,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Imperator.png',
        strength: 0,
        class: "Politician",
        display_class: "Politician",
        name: "Imperator",
        disPlay_name: "Imperator",
        ability: "Ruthless_Tactics",
        ability_desc: " Ruthless Tactics - Choose a class, and halve the overall strength of that class for your opponent.",
        lock: false
    },
    {
        id: 17,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Legionnaire.png',
        strength: 2,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Legionnaire",
        disPlay_name: "Legionnaire",
        ability: "The_Machine",
        ability_desc: "The Machine - Double unit strength for each other legionnaire card in play.",
        lock: false
    },
    {
        id: 18,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Legionnaire.png',
        strength: 2,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Legionnaire",
        disPlay_name: "Legionnaire",
        ability: "The_Machine",
        ability_desc: "The Machine - Double unit strength for each other legionnaire card in play.",
        lock: false
    },
    {
        id: 19,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Legionnaire.png',
        strength: 2,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Legionnaire",
        disPlay_name: "Legionnaire",
        ability: "The_Machine",
        ability_desc: "The Machine - Double unit strength for each other legionnaire card in play.",
        lock: false
    },
    {
        id: 20,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Magistrate.png',
        strength: 0,
        class: "Politician",
        display_class: "Politician",
        name: "Magistrate",
        disPlay_name: "Magistrate",
        ability: "Persuasive_Speech",
        ability_desc: "Persuasive Speech - Pick the enemy troop with the lowest strength on the field and move them to your side.",
        lock: false
    },
    {
        id: 21,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Magnus.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Magnus",
        disPlay_name: "Magnus",
        ability: "Master_Spy",
        ability_desc: "Master Spy - Pick a card from your Legion, and a card from your discard pile, and put them in your hand.",
        lock: false
    },
    {
        id: 22,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Marus.png',
        strength: 8,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Marus",
        disPlay_name: "Marus",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 23,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Mercenary.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Mercenary",
        disPlay_name: "Mercenary",
        ability: "Bought_and_Paid_For",
        ability_desc: "Bought and Paid For - If still active after winning a round, the card remains on the playing Field during the following round",
        lock: false
    },
    {
        id: 24,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Mercenary.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Mercenary",
        disPlay_name: "Mercenary",
        ability: "Bought_and_Paid_For",
        ability_desc: "Bought and Paid For - If still active after winning a round, the card remains on the playing Field during the following round.",
        lock: false
    },
    {
        id: 25,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Mercenary.png',
        strength: 4,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Mercenary",
        disPlay_name: "Mercenary",
        ability: "Bought_and_Paid_For",
        ability_desc: "Bought and Paid For - If still active after winning a round, the card remains on the playing Field during the following round.",
        lock: false
    },
    {
        id: 26,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Remus.png',
        strength: 10,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Remus",
        disPlay_name: "Remus",
        ability: "Son_of_the_Wolf",
        ability_desc: "Son of the Wolf - Choose any enemy card on the battlefield and discard it.",
        lock: false
    },
    {
        id: 27,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Slingers.png ',
        strength: 2,
        class: "Ranged",
        display_class: "Ranged",
        name: "Slinger",
        disPlay_name: "Slinger",
        ability: "A_Stones_Throw",
        ability_desc: "A Stone’s Throw - Halve the strength of the weakest enemy card(s).",
        lock: false
    },
    {
        id: 28,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Slingers.png ',
        strength: 2,
        class: "Ranged",
        display_class: "Ranged",
        name: "Slinger",
        disPlay_name: "Slinger",
        ability: "A_Stones_Throw",
        ability_desc: "A Stone’s Throw - Halve the strength of the weakest enemy card(s).",
        lock: false
    },
    {
        id: 29,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Slingers.png ',
        strength: 2,
        class: "Ranged",
        display_class: "Ranged",
        name: "Slinger",
        disPlay_name: "Slinger",
        ability: "A_Stones_Throw",
        ability_desc: "A Stone’s Throw - Halve the strength of the weakest enemy card(s).",
        lock: false
    },
    {
        id: 30,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Speculatores.png',
        strength: 4,
        class: "Scout",
        display_class: "Scout",
        name: "Speculatores",
        disPlay_name: "Speculatores",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 31,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Speculatores.png',
        strength: 4,
        class: "Scout",
        display_class: "Scout",
        name: "Speculatores",
        disPlay_name: "Speculatores",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 32,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Vettius.png',
        strength: 8,
        class: "Heavy_Soldier",
        display_class: "Heavy Soldier",
        name: "Vettius",
        disPlay_name: "Vettius",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 33,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Villagers.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Villagers",
        disPlay_name: "Villagers",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 34,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Villagers.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Villagers",
        disPlay_name: "Villagers",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 35,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Villagers.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Villagers",
        disPlay_name: "Villagers",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 36,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Villagers.png',
        strength: 1,
        class: "Light_Soldier",
        display_class: "Light Soldier",
        name: "Villagers",
        disPlay_name: "Villagers",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 37,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/ramulus-cards/vEmpire card Xena.png',
        strength: 7,
        class: "Ranged",
        display_class: "Ranged",
        name: "Xena",
        disPlay_name: "Xena",
        ability: "None",
        ability_desc: "None",
        lock: false
    },
    {
        id: 39,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Fog of War.png',
        strength: 0,
        class: "Status_Effect",
        display_class: "Status Effect",
        name: "Fog_of_War",
        disPlay_name: "Fog of War",
        ability: "Fog_of_War",
        ability_desc: "Fog of War - Halve the strength of all Ranged Troops on the field.",
        lock: false
    },
    {
        id: 40,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Fog of War.png',
        strength: 0,
        class: "Status_Effect",
        display_class: "Status Effect",
        name: "Fog_of_War",
        disPlay_name: "Fog of War",
        ability: "Fog_of_War",
        ability_desc: "Fog of War - Halve the strength of all Ranged Troops on the field.",
        lock: false
    },
    {
        id: 42,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Reinforcements.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Reinforcements",
        disPlay_name: "Reinforcements",
        ability: "Reinforcements",
        ability_desc: "Reinforcements - Pick a card from your Legion and put it in your hand.",
        lock: false
    }, {
        id: 43,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Reinforcements.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Reinforcements",
        disPlay_name: "Reinforcements",
        ability: "Reinforcements",
        ability_desc: "Reinforcements - Pick a card from your Legion and put it in your hand.",
        lock: false
    },
    {
        id: 44,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Sudis.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Sudis",
        disPlay_name: "Sudis",
        ability: "Sudis",
        ability_desc: "Sudis - When you play this card, the first troop played in the next round is discarded.",
        lock: false
    },
    {
        id: 45,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Sudis.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Sudis",
        disPlay_name: "Sudis",
        ability: "Sudis",
        ability_desc: "Sudis - When you play this card, the first troop played in the next round is discarded.",
        lock: false
    },
    {
        id: 46,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Laconian Shib.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Laconian_Shib",
        disPlay_name: "Laconian Shib",
        ability: "Laconian_Shib",
        ability_desc: "Laconian Shib- Reduce the Strength of all soldiers on foot by 1.",
        lock: false
    },
    {
        id: 47,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Laconian Shib.png',
        strength: 0,
        class: "Utility",
        display_class: "Utility",
        name: "Laconian_Shib",
        disPlay_name: "Laconian Shib",
        ability: "Laconian_Shib",
        ability_desc: "Laconian Shib- Reduce the Strength of all soldiers on foot by 1.",
        lock: false
    },
    {
        id: 41,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Praetorian Guard.png',
        strength: 0,
        class:"Utility",
        display_class:"Utility",
        name:"Praetorian_Guard",
        disPlay_name:"Praetorian Guard",
        ability: "Praetorian_Guard",
        ability_desc: "Praetorian Guard - Attach this card to any other troop to protect them from one negative effect from a enemy card. Discard after that attack.",
        lock:false
    },
    {
        id: 52,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire card Praetorian Guard.png',
        strength: 0,
        class:"Utility",
        display_class:"Utility",
        name:"Praetorian_Guard",
        disPlay_name:"Praetorian Guard",
        ability: "Praetorian_Guard",
        ability_desc: "Praetorian Guard - Attach this card to any other troop to protect them from one negative effect from a enemy card. Discard after that attack.",
        lock:false
    },
    {
        id: 38,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire+card+Filibuster.png',
        strength: 0,
        class: "Status_Effect",
        display_class: "Status Effect",
        name: "Filibuster",
        disPlay_name: "Filibuster",
        ability: "Filibuster",
        ability_desc: "Filibuster - Negate the effect of any active politician card.",
        lock: false
    },
    {
        id: 53,
        battleCard: 'https://playassets.s3.eu-west-1.amazonaws.com/universal-cards/vEmpire+card+Filibuster.png',
        strength: 0,
        class: "Status_Effect",
        display_class: "Status Effect",
        name: "Filibuster",
        disPlay_name: "Filibuster",
        ability: "Filibuster",
        ability_desc: "Filibuster - Negate the effect of any active politician card.",
        lock: false
    },
]